import streamlit as st
import datetime
import requests
import sys


BASE_URL = "http://localhost:8000"

st.set_page_config(
    page_title = "AI Trip Planner",
    page_icon = "✈️",
    layout="centered",
    initial_sidebar_state="expanded"
)


st.title("AI Trip Planner")

# Initialize chat history
if 'messages' not in st.session_state:
    st.session_state['messages'] = []

st.header("I help to plan trips and manage travel expenses efficiently!!!!")


with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("user input", placeholder="e.g. Plan a trip to THailand for 5 days")
    submit_button= st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:

        with st.spinner("Planning your trip..."):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer found.")
            markdown_content = f"""
            # AI Travel Plan

            =======================

            {answer}

            =======================

            Travel Plan Generated By AI. Please Verify everything from your end before finalizing the trip. Happy Journey!!

            """
            st.session_state['messages'].append({"user": user_input, "assistant": answer})
            st.markdown(markdown_content)

        else:
             st.error("ERROR: " + response.text)

    except Exception as e:
        st.error(f"The response failed due to {e}")
